name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.7.14=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.15=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.0=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=py310h5588dad_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.1=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310ha8f682b_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pywin32=311=py310h282bd7d_0
  - pyzmq=27.0.0=py310h656833d_0
  - setuptools=78.1.1=py310haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h5e9d12e_1
  - tornado=6.5.1=py310ha8f682b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - cachetools==5.5.2
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.74.0
      - idna==3.10
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - lightning-utilities==0.15.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.6.2
      - multidict==6.6.3
      - numpy==1.23.5
      - oauthlib==3.3.1
      - pandas==1.5.3
      - pillow==11.3.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - pytorch-lightning==1.9.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.1.3
      - scipy==1.10.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchinfo==1.7.2
      - torchmetrics==1.5.2
      - torchvision==0.14.1
      - tqdm==4.67.1
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - yarl==1.20.1
